<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class OccupationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $occupations = [
            'Miembros del poder ejecutivo y legislativo',
            'Personal directivo de la administración pública',
            'Directores y gerentes generales de servicios financieros, de telecomunicaciones y otros servicios a las empresas',
            'Directores y gerentes generales de salud, educación, servicio social, comunitario y organizaciones de membresía',
            'Directores y gerentes generales de comercio, medios de comunicación y otros servicios',
            'Directores y gerentes generales de producción de bienes, servicios públicos, transporte y construcción',
            'Directores y gerentes generales de servicios y procesos de negocio',
            'Gerentes financieros',
            'Gerentes de talento humano',
            'Gerentes de compras y adquisiciones',
            'Gerentes de otros servicios administrativos',
            'Gerentes de seguros, bienes raíces y corretaje financiero',
            'Gerentes de banca, crédito e inversiones',
            'Gerentes de otros servicios a las empresas',
            'Gerentes de empresas de telecomunicaciones',
            'Gerentes de servicios de correo y mensajería',
            'Gerentes de ingeniería',
            'Gerentes de investigación y desarrollo en ciencias naturales y aplicadas',
            'Gerentes de sistemas de información y procesamiento de datos',
            'Gerentes de servicios a la salud',
            'Gerentes de programas de política social y de salud',
            'Gerentes de programas de política de desarrollo económico',
            'Gerentes de programas de política educativa',
            'Otros gerentes de administración pública',
            'Directores y administradores de instituciones de educación y formación',
            'Gerentes de servicios social, comunitario y correccional',
            'Gerentes de biblioteca, museo y galería de arte',
            'Gerentes de medios de comunicación y artes escénicas',
            'Directores y gerentes de recreación, esparcimiento y deportes',
            'Gerentes de ventas, mercadeo y publicidad',
            'Gerentes de comercio exterior',
            'Gerentes de comercio al por menor',
            'Gerentes de restaurantes y servicios de alimentos',
            'Gerentes de servicios hoteleros',
            'Oficiales de las fuerzas militares',
            'Oficiales de policía',
            'Oficiales de bomberos',
            'Oficiales del cuerpo de custodia y vigilancia',
            'Gerentes de otros servicios',
            'Gerentes de producción primaria (excepto agricultura)',
            'Gerentes de producción agrícola, pecuaria, acuícola y pesquero',
            'Gerentes de construcción',
            'Gerentes de transporte y distribución',
            'Gerentes de logística',
            'Gerentes cadena de suministro',
            'Gerentes y directores de servicios portuarios',
            'Gerentes de operación de instalaciones físicas',
            'Gerentes de mantenimiento',
            'Gerentes de producción industrial',
            'Gerentes de empresas de servicios públicos',
            'Contadores',
            'Analistas, asesores y agentes de mercado financiero',
            'Auditores financieros y contables',
            'Profesionales de talento humano',
            'Profesionales y analistas de gestión y organización',
            'Evaluadores de competencias laborales',
            'Archivistas',
            'Profesionales de formación y desarrollo de personal',
            'Profesionales en operaciones y servicios portuarios',
            'Supervisores de empleados de apoyo administrativo',
            'Jefes y supervisores de entidades financieras',
            'Supervisores y coordinadores de procesos de negocio, empleados de información y servicio al cliente',
            'Supervisores de empleados de correo y mensajería',
            'Supervisores de almacenamiento, inventario y distribución',
            'Coordinadores y supervisores en operaciones y servicios portuarios',
            'Asistentes administrativos',
            'Administradores de propiedad horizontal',
            'Asistentes de talento humano',
            'Asistentes de compras',
            'Asistentes de juzgados, tribunales y afines',
            'Funcionarios de aduanas, impuestos, migración y seguridad social',
            'Asistentes de comercio exterior',
            'Técnicos en archivística',
            'Asistentes contables',
            'Analistas, asistentes y asesores de servicios financieros',
            'Evaluadores, ajustadores, analistas y liquidadores de seguros',
            'Agentes de aduana',
            'Asistentes financieros',
            'Asistentes de tesorería',
            'Asistentes de mercadeo, publicidad y comunicaciones',
            'Secretarios',
            'Recepcionistas y operadores de conmutador',
            'Digitadores',
            'Transcriptores y relatores',
            'Digitalizadores',
            'Auxiliares contables, de tesorería y financieros',
            'Cajeros de servicios financieros',
            'Auxiliares de servicios financieros',
            'Auxiliares de cartera y cobranzas',
            'Auxiliares de nómina y prestaciones',
            'Avaluadores',
            'Auxiliares administrativos',
            'Auxiliares de talento humano',
            'Auxiliares de tribunales',
            'Auxiliares de archivo y registro',
            'Auxiliares administrativos en salud',
            'Auxiliares de aduana',
            'Auxiliares de biblioteca',
            'Auxiliares de publicación y afines',
            'Auxiliares de información y servicio al cliente',
            'Auxiliares de estadística y encuestadores',
            'Auxiliares de correo y servicio postal',
            'Carteros y mensajeros',
            'Auxiliares de almacén',
            'Auxiliares de compras e inventarios',
            'Operadores de radio y despachadores',
            'Programadores de rutas y tripulaciones',
            'Operadores telefónicos',
            'Físicos y astrónomos',
            'Químicos',
            'Geólogos, geoquímicos y geofísicos',
            'Meteorólogos',
            'Oceanógrafos',
            'Profesionales en metrología',
            'Biólogos, biotecnólogos, botánicos, zoólogos y afines',
            'Expertos forestales',
            'Expertos agrícolas y pecuarios',
            'Administradores ambientales',
            'Extensionistas agropecuarios',
            'Agroecólogos',
            'Ingenieros en construcción y obras civiles',
            'Ingenieros mecánicos',
            'Ingenieros electricistas',
            'Ingenieros electrónicos',
            'Ingenieros químicos',
            'Ingenieros de automatización e instrumentación',
            'Ingenieros de telecomunicaciones',
            'Ingenieros navales',
            'Ingenieros industriales y de fabricación',
            'Ingenieros de materiales y metalurgia',
            'Ingenieros de minas',
            'Ingenieros de petróleos',
            'Ingenieros de tecnologías de la información',
            'Otros ingenieros nca',
            'Ingenieros y productores de audio y sonido',
            'Arquitectos',
            'Urbanistas y planificadores del uso del suelo',
            'Ingenieros topográficos',
            'Diseñadores industriales',
            'Matemáticos, estadísticos y actuarios',
            'Analistas de sistemas informáticos',
            'Administradores de servicios de tecnologías de la información',
            'Desarrolladores de aplicaciones informáticas y digitales',
            'Técnicos en química aplicada',
            'Técnicos en geología y minería',
            'Técnicos en meteorología',
            'Técnicos en metrología',
            'Técnicos en ciencias biológicas y biotecnológicas (excluyendo la medicina)',
            'Técnicos en recursos naturales',
            'Técnicos en prevención, gestión y control ambiental',
            'Gemólogos',
            'Técnicos en construcción y arquitectura',
            'Técnicos en mecánica y construcción mecánica',
            'Técnicos en fabricación industrial',
            'Técnicos en electricidad',
            'Técnicos en electrónica',
            'Técnicos en automatización e instrumentación',
            'Técnicos en instrumentos de aeronavegación',
            'Técnicos en telecomunicaciones',
            'Dibujantes técnicos',
            'Topógrafos',
            'Técnicos en cartografía',
            'Inspectores de pruebas no destructivas',
            'Inspectores de sanidad, seguridad y salud ocupacional',
            'Inspectores de construcción',
            'Inspectores de equipos de transporte e instrumentos de medición',
            'Inspectores de productos agrícolas, pecuarios y de pesca',
            'Inspectores de riego agrícola',
            'Coordinadores de sistemas integrados de gestión',
            'Pilotos, ingenieros e instructores de vuelo',
            'Controladores de tráfico aéreo',
            'Capitanes y oficiales de cubierta',
            'Oficiales de máquinas',
            'Controladores de tráfico ferroviario y marítimo',
            'Despachadores de aeronaves',
            'Técnicos en tecnologías de la información',
            'Asistentes en saneamiento ambiental',
            'Auxiliares de laboratorio',
            'Auxiliares de seguridad en el trabajo',
            'Operarios de exploración geofísica y geológica',
            'Auxiliares en automatización e instrumentación industrial',
            'Técnicos en asistencia y soporte de tecnologías de la información',
            'Médicos especialistas',
            'Médicos generales',
            'Odontólogos',
            'Veterinarios',
            'Optómetras',
            'Otras ocupaciones profesionales en diagnóstico y tratamiento de la salud nca',
            'Farmacéuticos y químicos farmacéuticos',
            'Dietistas y nutricionistas',
            'Audiólogos y terapeutas del lenguaje',
            'Fisioterapeutas',
            'Terapeutas ocupacionales',
            'Enfermeros',
            'Instrumentadores quirúrgicos',
            'Psicólogos',
            'Profesionales de la salud, la higiene laboral y ambiental',
            'Técnicos de laboratorio médico y patología',
            'Técnicos en terapia respiratoria y cardiovascular',
            'Técnicos y tecnólogos en imágenes diagnósticas',
            'Técnicos en radioterapia',
            'Técnicos en medicina nuclear',
            'Regentes de farmacia',
            'Higienistas dentales',
            'Técnicos en mecánica oftálmica',
            'Practicantes de medicina alternativa',
            'Asistentes de ambulancia y otras ocupaciones paramédicas',
            'Técnicos en desarrollo de productos para la asistencia en salud',
            'Guardavidas',
            'Auxiliares en enfermería',
            'Auxiliares de salud oral',
            'Auxiliares en salud pública',
            'Auxiliares de laboratorio clínico',
            'Auxiliares en servicios farmacéuticos',
            'Otros auxiliares de servicios a la salud nca',
            'Técnicos en mecánica dental',
            'Jueces',
            'Abogados',
            'Profesores de instituciones de educación superior',
            'Especialistas en procesos pedagógicos',
            'Profesores e instructores de formación para el trabajo',
            'Profesores de educación básica secundaria y media',
            'Profesores de educación básica primaria',
            'Profesores de preescolar',
            'Orientadores educativos',
            'Pedagogo reeducador',
            'Trabajadores sociales y consultores de familia',
            'Ministros del culto',
            'Sociólogos, antropólogos y afines',
            'Filósofos, filólogos y afines',
            'Consultores, investigadores y analistas de política económica',
            'Consultores y funcionarios de desarrollo económico',
            'Investigadores, consultores y funcionarios de políticas sociales de salud y de educación',
            'Funcionarios de programas exclusivos de la administración pública',
            'Investigadores, consultores y funcionarios de políticas de ciencias naturales y aplicadas',
            'Profesionales en gestión de riesgo de desastres',
            'Profesionales en ciencias forenses',
            'Asistentes en servicios social y comunitario',
            'Consejeros de servicios de empleo',
            'Instructores y profesores de personas en condición de discapacidad',
            'Otros instructores',
            'Ocupaciones religiosas',
            'Investigadores criminalísticos y judiciales',
            'Asistentes legales y afines',
            'Auxiliares de educación para la primera infancia',
            'Auxiliares sociales',
            'Bibliotecólogos',
            'Restauradores',
            'Curadores',
            'Escritores',
            'Editores y redactores',
            'Periodistas',
            'Traductores e intérpretes',
            'Ocupaciones profesionales en relaciones públicas y comunicaciones',
            'Profesionales en mercadeo y publicidad',
            'Productores, directores artísticos y ocupaciones relacionadas',
            'Intérpretes musicales',
            'Compositores coreográficos de danza',
            'Actores',
            'Pintores, escultores y otros artistas visuales',
            'Directores e investigadores musicales',
            'Autores y compositores musicales',
            'Diseñadores gráficos',
            'Ocupaciones técnicas relacionadas con museos y galerías',
            'Técnicos en biblioteca',
            'Técnicos en promoción y animación a la lectura y la escritura',
            'Fotógrafos',
            'Operadores de cámara de cine y televisión',
            'Técnicos en diseño y arte gráfico',
            'Técnicos en transmisión de radio y televisión',
            'Otras ocupaciones técnicas en cine, televisión y artes escénicas nca',
            'Ocupaciones de asistencia en cine, televisión y artes escénicas',
            'Productores de campo para cine y televisión',
            'Locutores de radio, televisión y otros medios de comunicación',
            'Curadores y supervisores musicales',
            'Otros artistas nca',
            'Diseñadores de interiores',
            'Diseñadores de teatro, moda, exhibición y otros diseñadores creativos',
            'Patronistas de productos de tela, cuero y piel',
            'Ilustradores',
            'Graficadores de imágenes computarizadas',
            'Deportistas',
            'Entrenadores y preparadores físicos',
            'Árbitros',
            'Ceramistas',
            'Tejedores',
            'Artesanos trabajos en maderables y no maderables',
            'Artesanos trabajos en cuero',
            'Artesanos trabajos en metal',
            'Otros artesanos nca',
            'Artesanos trabajos en vidrio',
            'Artesanos trabajos en materiales líticos',
            'Artesanos trabajos en papel',
            'Operadores de audio y sonido',
            'Ejecutantes musicales',
            'Auxiliares de producción de audio y sonido',
            'Interpretes para la danza',
            'Otros actores',
            'Desfibradores de fibras naturales',
            'Supervisores de ventas',
            'Administradores y supervisores de comercio al por menor',
            'Supervisores de servicios de alimentos',
            'Supervisores de aseo, mantenimiento y limpieza en oficinas, hoteles, otros establecimientos, área y vía pública',
            'Sommeliers',
            'Supervisores de servicios de alojamiento y hospedaje',
            'Suboficiales de las fuerzas militares',
            'Suboficiales y nivel ejecutivo de la policía',
            'Supervisores de vigilantes',
            'Suboficiales del cuerpo de custodia y vigilancia',
            'Suboficiales de bomberos',
            'Poligrafistas',
            'Agentes y corredores de seguros',
            'Agentes de bienes raíces',
            'Vendedores de ventas técnicas',
            'Agentes de compras e intermediarios',
            'Representante de servicios especializados BPO',
            'Administradores de comunidades virtuales',
            'Agentes y promotores artísticos',
            'Coordinadores y productores de eventos y espectáculos',
            'Chefs',
            'Auxiliares de vuelo y sobrecargos',
            'Tanatopractores',
            'Coordinadores de servicios funerarios',
            'Intérpretes de lengua de señas colombiana - español',
            'Guías-intérpretes',
            'Guías de turismo',
            'Tatuadores',
            'Vendedores de ventas no técnicas',
            'Auxiliares de promoción artística',
            'Asesores integrales de imagen',
            'Vendedores de mostrador',
            'Mercaderistas e impulsadores',
            'Cajeros de comercio',
            'Modelos',
            'Agentes de viajes',
            'Empleados de ventas y servicios de líneas aéreas, marítimas y terrestres',
            'Empleados de recepción hotelera',
            'Informadores turísticos',
            'Recreadores',
            'Operadores de juegos mecánicos y de salón',
            'Auxiliares de producción audiovisual, de eventos y espectáculos',
            'Cortadores de carne para comercio mayorista y al detal',
            'Panaderos y pasteleros',
            'Meseros y capitán de meseros',
            'Bartender',
            'Cocineros',
            'Baristas',
            'Transformadores de caña panelera',
            'Inspectores de policía',
            'Funcionarios de regulación',
            'Auxiliares de policía',
            'Bomberos',
            'Guardianes de prisión',
            'Soldados',
            'Vigilantes y guardias de seguridad',
            'Técnicos investigadores criminalísticos y judiciales',
            'Acompañantes domiciliarios',
            'Auxiliares del cuidado de niños',
            'Peluqueros',
            'Trabajadores del cuidado de animales',
            'Auxiliares de servicios funerarios',
            'Astrólogos, adivinadores y relacionados',
            'Manicuristas y pedicuristas',
            'Cosmetólogos esteticistas',
            'Maquilladores',
            'Agentes de tránsito',
            'Técnicos operativos de tránsito',
            'Trabajadores de estación de servicio',
            'Otras ocupaciones elementales de las ventas',
            'Ayudantes de establecimientos de alimentos y bebidas',
            'Aseadores y servicio doméstico',
            'Aseadores especializados y fumigadores',
            'Recolectores de material para reciclaje',
            'Auxiliares de servicios a viajeros',
            'Auxiliares de servicios de recreación y deporte',
            'Empleados de lavandería',
            'Otras ocupaciones elementales de los servicios nca',
            'Auxiliares de servicios hoteleros',
            'Operarios de cementerios',
            'Anfitriones turísticos locales',
            'Administradores de explotación acuícola y jefes de laboratorio de cultivo o producción acuícola',
            'Supervisores de minería y canteras',
            'Supervisores de perforación y servicios, pozos de petróleo y gas',
            'Inspectores de sistemas e instalaciones de gas',
            'Supervisores y analistas de producción de hidrocarburos',
            'Supervisores de producción agrícola',
            'Supervisores de producción pecuaria',
            'Supervisores de explotación forestal y silvicultura',
            'Agricultores y administradores agropecuarios',
            'Contratistas de servicios agrícolas y relacionados',
            'Supervisores de servicios de jardinería y viverismo',
            'Capitanes y patrones de pesca',
            'Operarios de apoyo y servicios en minería bajo tierra',
            'Operarios de apoyo y servicios en perforación de petróleo y gas',
            'Mineros de producción bajo tierra',
            'Perforadores de pozos de gas y petróleo y trabajadores relacionados',
            'Inspectores de construcción de oleoductos y gasoductos',
            'Operadores de equipo minero',
            'Operadores de producción de hidrocarburos',
            'Operarios de servicios a pozos de hidrocarburos',
            'Operarios torres de perforación de hidrocarburos',
            'Trabajadores de explotación forestal',
            'Trabajadores de silvicultura y forestación',
            'Trabajadores agrícolas',
            'Trabajadores pecuarios',
            'Trabajadores de vivero',
            'Trabajadores del campo',
            'Trabajadores de plantas de incubación artificial',
            'Rayadores de caucho',
            'Operarios de riego agrícola',
            'Pescadores',
            'Operario acuícola',
            'Técnico acuícola en sistemas de reproducción',
            'Técnico acuícola en sistemas de levante y engorde',
            'Obreros y ayudantes de minería',
            'Obreros y ayudantes de producción en pozos de petróleo y gas',
            'Obreros agropecuarios',
            'Jardineros',
            'Supervisores de ajustadores de máquinas herramientas',
            'Supervisores de electricidad y telecomunicaciones',
            'Supervisores de instalación de tuberías',
            'Supervisores de moldeo de forja y montaje de estructuras metálicas',
            'Supervisores de carpintería',
            'Supervisores de mecánica',
            'Supervisores de operación de equipo pesado',
            'Maestros generales de obra y supervisores de construcción, instalación y reparación',
            'Supervisores de operación de transporte ferroviario',
            'Supervisores de operación de transporte terrestre (no ferroviario)',
            'Ajustadores y operadores de máquinas herramientas',
            'Modelistas y matriceros',
            'Electricistas industriales',
            'Electricistas residenciales',
            'Instaladores de redes de energía eléctrica',
            'Técnicos instaladores de redes y líneas de telecomunicaciones',
            'Auxiliares técnicos de instalación, mantenimiento y reparación de sistemas de telecomunicaciones',
            'Operarios de mantenimiento y servicio de televisión por cable',
            'Oficiales fontaneros y plomeros',
            'Instaladores de tuberías para sistemas de extinción de incendios',
            'Instaladores de redes y equipos a gas',
            'Chapistas, caldereros y paileros',
            'Soldadores',
            'Montadores de estructuras metálicas',
            'Ornamentistas, forjadores y herreros',
            'Tuberos',
            'Carpinteros',
            'Ebanistas',
            'Oficiales de construcción',
            'Trabajadores en concreto, hormigón y enfoscado',
            'Enchapadores',
            'Techadores',
            'Instaladores de material aislante',
            'Pintores y empapeladores',
            'Instaladores de pisos',
            'Revocadores',
            'Mecánicos industriales',
            'Mecánicos de maquinaria textil, confección, cuero, calzado y marroquinería',
            'Mecánicos de equipo pesado',
            'Mecánicos de aviación',
            'Técnicos de aire acondicionado y refrigeración',
            'Mecánicos de vehículos automotores',
            'Electricistas de vehículos automotores',
            'Mecánicos de motos',
            'Latoneros',
            'Reparadores de aparatos electrodomésticos',
            'Mecánicos electricistas',
            'Auxiliares técnicos en electrónica',
            'Mecánicos de otras pequeñas máquinas y motores',
            'Instaladores residenciales y comerciales',
            'Operarios de mantenimiento de instalaciones de abastecimiento de agua y gas',
            'Vidrieros',
            'Ayudantes electricistas',
            'Ayudantes de mecánica',
            'Otros reparadores nca',
            'Tapiceros',
            'Sastres, modistos, peleteros y sombrereros',
            'Zapateros y afines',
            'Joyeros y relojeros',
            'Tipógrafos',
            'Cerrajeros y afines',
            'Buzos',
            'Operadores de máquinas estacionarias y equipo auxiliar',
            'Operadores de plantas de generación y distribución de energía',
            'Operadores de planta de gas',
            'Operadores de grúa',
            'Perforadores y operarios de voladura para minería de superficie de canteras y construcción',
            'Perforadores de pozos de agua',
            'Operadores de equipo pesado (excepto grúa)',
            'Operadores de equipo para limpieza de vías y alcantarillado',
            'Operadores de maquinaria agrícola',
            'Maquinistas de transporte ferroviario',
            'Guardafrenos y otros operadores ferroviarios',
            'Conductores de vehículos pesados',
            'Operadores de bus, metro y otros medios de transporte colectivo y masivo',
            'Conductores de vehículos livianos',
            'Conductores de transporte de alimentos',
            'Marineros de cubierta',
            'Marineros de sala de máquinas',
            'Operadores de pequeñas embarcaciones',
            'Operarios de rampa de transporte aéreo',
            'Operarios portuarios',
            'Operarios de cargue y descargue de materiales',
            'Aparejadores',
            'Ayudantes y obreros de construcción',
            'Ayudantes de otros oficios',
            'Obreros y ayudantes de obras públicas',
            'Ayudantes de transporte automotor',
            'Ayudantes y operarios de barrido y mantenimiento de áreas públicas',
            'Directores de planta de procesamiento de alimentos y bebidas',
            'Jefe de laboratorio de alimentos',
            'Supervisores de tratamiento de metales y minerales',
            'Supervisores de procesamiento de químico, petróleo, gas y tratamiento de agua y generación de energía',
            'Supervisores de procesamiento de alimentos y bebidas',
            'Supervisores de fabricación y procesamiento de productos de plástico y caucho',
            'Supervisores de procesamiento de la madera y producción de pulpa y papel',
            'Supervisores de procesamiento textil',
            'Inspectores de control de calidad, procesamiento de alimentos y bebidas',
            'Supervisores de ensamble de vehículos de motor',
            'Supervisores de fabricación de productos electrónicos',
            'Supervisores de fabricación de productos eléctricos',
            'Supervisores de fabricación de muebles y accesorios',
            'Supervisores de fabricación de productos de tela, cuero y piel',
            'Supervisores de impresión y ocupaciones relacionadas',
            'Supervisores de fabricación de otros productos mecánicos y metálicos',
            'Supervisores de fabricación y ensamble de otros productos nca',
            'Inspectores de vehículos de motor',
            'Operadores de control central de procesos, tratamiento de metales y minerales',
            'Operadores de procesos, químicos, gas y petróleo',
            'Operadores de control de procesos, producción de pulpa',
            'Operadores de control de procesos, fabricación de papel',
            'Impresores de artes gráficas',
            'Pre-prensistas de artes gráficas',
            'Operarios de terminados y acabados de artes gráficas',
            'Operadores de máquinas, tratamiento de metales y minerales',
            'Trabajadores de fundición, moldeadores y macheros',
            'Operadores de fabricación, moldeo y acabado del vidrio',
            'Operadores de moldeo de arcilla, piedra y concreto',
            'Inspectores de control de calidad, tratamiento de metales y minerales',
            'Operadores de máquinas de planta química',
            'Operadores de máquinas para fabricar productos de material plástico',
            'Operadores de máquinas para fabricar y procesar productos de caucho',
            'Operadores de plantas de tratamiento de agua',
            'Operadores de rellenos sanitarios',
            'Operadores de máquinas para procesamiento de la madera',
            'Operadores de máquinas para la producción de pulpa',
            'Operadores de máquinas para la fabricación de papel',
            'Operadores de máquinas para la fabricación de productos de papel',
            'Inspectores de control de calidad, procesamiento de la madera',
            'Operadores de máquinas para la preparación de fibras textiles',
            'Operadores de telares y otras máquinas tejedoras',
            'Operadores de máquinas de tintura, acabado textil y prendas',
            'Analistas de calidad, textiles',
            'Operadores de máquinas para coser y bordar',
            'Cortadores de tela, cuero y piel',
            'Operadores de máquinas y trabajadores relacionados con la fabricación de calzado y marroquinería',
            'Trabajadores del tratamiento de pieles y cueros',
            'Inspectores de control de calidad, fabricación de productos de tela, piel y cuero',
            'Operadores de control de procesos y máquinas para la elaboración de alimentos y bebidas',
            'Operarios de planta de beneficio animal',
            'Operarios de planta de procesamiento y empaque de pescado y mariscos',
            'Operarios de máquinas para la elaboración de productos de tabaco',
            'Procesadores fotográficos y de películas',
            'Ensambladores de vehículos automotores',
            'Ensambladores de productos electrónicos',
            'Ensambladores e inspectores de aparatos y equipo eléctrico',
            'Ensambladores, fabricantes e inspectores de transformadores y motores eléctricos industriales',
            'Ensambladores e inspectores de productos mecánicos',
            'Ensambladores e inspectores de ensamble de aeronaves',
            'Operadores de máquinas e inspectores de la fabricación de productos y componentes eléctricos',
            'Ensambladores e inspectores de embarcaciones',
            'Ensambladores e inspectores de muebles y accesorios',
            'Operarios de acabado de muebles',
            'Ensambladores de productos plásticos e inspectores',
            'Operarios de tratamiento térmico y recubrimientos metálicos',
            'Pintores en procesos de manufactura',
            'Otros ensambladores e inspectores nca',
            'Auxiliares de producción gráfica',
            'Operadores de máquinas para el trabajo de la madera',
            'Operadores de máquinas para el trabajo del metal',
            'Operadores de máquinas para forja',
            'Operadores de máquinas de soldadura',
            'Operadores de máquinas para la fabricación de otros productos metálicos nca',
            'Operadores de máquinas para la fabricación de otros productos nca',
            'Obreros y ayudantes en el tratamiento de metales y minerales',
            'Ayudantes en la fabricación metálica',
            'Obreros y ayudantes de planta química',
            'Obreros y ayudantes en el procesamiento de la madera y producción de pulpa y papel',
            'Auxiliares en el procesamiento de alimentos y bebidas',
            'Otros obreros y ayudantes en fabricación y procesamiento nca'
        ];

        foreach ($occupations as $occupation) {
            DB::table('occupations')->insert(['occupation_name' => $occupation]);
        }
    }
}
